In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/rishirokde-official/Python-for-Data-Science/refs/heads/main/python-for-data-science-main/02.Intro%20to%20Pandas/StudentsPerformance.csv")

In [3]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [4]:
df.head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88

In [5]:
df.tail(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [6]:
df.shape

(1000, 8)

In [8]:
pd.set_option('display.max_rows',100)

Basic attribute , methods and functions

In [9]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [12]:
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [14]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

Functions

In [15]:
len(df)

1000

In [16]:
max(df.index)

999

In [17]:
min(df.index)

0

In [18]:
type(df)

pandas.core.frame.DataFrame

In [20]:
round(df,2).head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88

selecting one column

In [23]:
df['gender']
df['gender'].index
df['gender'].head(2)

0    female
1    female
Name: gender, dtype: object

In [27]:
df["math score"].head(1)

0    72
Name: math score, dtype: int64

Selecting two or more columns

In [36]:
df[['gender','math score','writing score','reading score']].head(1)

   gender  math score  writing score  reading score
0  female          72             74             72

In [37]:
df['language score']=70

In [53]:
df.head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,0,218
1,female,group C,some college,standard,completed,69,90,88,1,247


Adding a new column with an array

In [39]:
import numpy as np

In [42]:
language_score=np.arange(0,1000)

In [43]:
len(language_score)

1000

In [44]:
df['language score']=language_score

In [52]:
df.head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,0,218
1,female,group C,some college,standard,completed,69,90,88,1,247

Math Operations

In [47]:
df['math score'].sum()
df['math score'].count()
df['math score'].mean()
df['math score'].max()
df['math score'].min()
df['math score'].std()

15.163080096009468

Operations in rows

In [48]:
df['math score']+df['reading score']+df['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [50]:
df['average']=df['math score']+df['reading score']+df['writing score']

In [51]:
df.head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,0,218
1,female,group C,some college,standard,completed,69,90,88,1,247

value counts()

In [54]:
df['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

sorting

In [58]:
df.sort_values('math score',ascending=False).head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,average
451,female,group E,some college,standard,none,100,92,97,451,289
458,female,group E,bachelor's degree,standard,none,100,100,100,458,300