In [1]:
import pandas as pd

PIVOT TABLE IS USE TO CONVERT ROWS INTO COLUMNS AND COLUMNS INTO ROWS

In [24]:
df=pd.read_csv("/content/gdp (1).csv",encoding='Latin')

In [25]:
df

      unid wbid      country  year        SES       gdppc  yrseduc  popshare
0        4  AFG  Afghanistan  1970   3.474212   709.00000      NaN  0.003097
1        4  AFG  Afghanistan  1920  26.968016   731.75677      NaN  0.003245
2        4  AFG  Afghanistan  1990   1.269530   604.00000      NaN  0.002347
3        4  AFG  Afghanistan  1960  15.763076   739.00000      NaN  0.003039
4        4  AFG  Afghanistan  2000   2.061114   565.00000      NaN  0.003309
...    ...  ...          ...   ...        ...         ...      ...       ...
2081   716  ZWE     Zimbabwe  1940  52.746567   813.00000      NaN  0.001113
2082   716  ZWE     Zimbabwe  2010  27.091389  1388.97300      NaN  0.002074
2083   716  ZWE     Zimbabwe  1990  59.110970  2526.07230      NaN  0.002039
2084   716  ZWE     Zimbabwe  1900  54.722645   601.00000      NaN  0.000996
2085   716  ZWE     Zimbabwe  1960  53.811077   938.00000      NaN  0.001268

[2086 rows x 8 columns]

PIVOT ()

In [28]:
# reshape the dataframe with .pivot()
df_pivot = df.pivot(index="year", columns="country", values="gdppc")
df_pivot

country,Afghanistan,Albania,Algeria,Angola,Argentina,Armenia,Australia,Austria,Bahrain,Bangladesh,...,Ukraine,United Arab Emirates,United Kingdom,United States,Uruguay,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
year,,,,,,,,,,,,,,,,,,,,,
1880,585.46509,522.00000,819.18604,533.66669,1731.500,1041.0000,4285.000,2079.000,811.76746,566.66669,...,1041.0000,811.76746,3477.000,3184.000,2082.0000,653.000,556.62793,811.76746,533.66669,533.66669
1890,635.93024,598.00000,923.37207,567.33331,2152.000,1139.0000,4458.000,2443.000,881.53491,587.33331,...,1139.0000,881.53491,4009.000,3392.000,2147.0000,737.000,608.25580,881.53491,567.33331,567.33331
1900,686.39532,685.00000,1027.55810,601.00000,2756.000,1237.0000,4013.000,2882.000,951.30231,608.00000,...,1237.0000,951.30231,4492.000,4091.000,2219.0000,821.000,659.88373,951.30231,601.00000,601.00000
1910,736.86047,780.00000,1131.74410,628.69232,3822.000,1430.0769,5210.000,3290.000,1021.06980,661.84613,...,1430.0769,1021.06980,4611.000,4964.000,3136.0000,886.000,711.51166,1021.06980,628.69232,628.69232
1920,731.75677,861.31250,1201.21620,682.62964,3473.000,1432.9333,4766.000,2412.000,1242.91890,651.89191,...,1432.9333,3833.67580,4548.000,5552.000,2674.0000,1173.000,713.94592,1017.21620,682.62964,682.62964
1930,702.83783,929.57141,1255.81080,747.81482,4080.000,1448.0000,4708.000,3586.000,1529.94590,614.59460,...,1448.0000,7821.78370,5441.000,6213.000,4301.0000,3444.000,695.29730,981.81079,747.81482,747.81482
1940,673.91895,965.28571,1310.40540,813.00000,4161.000,2144.0000,6166.000,3959.000,1816.97300,577.29730,...,2144.0000,11809.89200,6856.000,7010.000,3661.0000,4045.000,676.64862,946.40540,813.00000,813.00000
1950,645.00000,1001.00000,1365.00000,1052.00000,4987.000,2841.0000,7412.000,3706.000,2104.00000,540.00000,...,2841.0000,15798.00000,6939.000,9561.000,4659.0000,7462.000,658.00000,911.00000,661.00000,701.00000
1960,739.00000,1451.00000,2088.00000,1253.00000,5559.000,3945.0000,8791.000,6519.000,2843.00000,545.00000,...,3945.0000,22433.00000,8645.000,11328.000,4960.0000,9646.000,799.00000,964.00000,960.00000,938.00000
1970,709.00000,2004.00000,2249.00000,1768.00000,7302.000,5575.0000,12024.000,9747.000,3788.00000,630.00000,...,5575.0000,24552.00000,10767.000,15030.000,5184.0000,10672.000,735.00000,1230.00000,1073.00000,1282.00000
1980,690.00000,2347.00000,3152.00000,961.00000,8206.000,6116.5884,14412.000,13759.000,4388.00000,549.00000,...,5378.1763,27709.00000,12931.000,18577.000,6555.0000,10139.000,757.00000,2290.00000,911.00000,1295.00000
1990,604.00000,4557.40820,10238.88400,4806.43020,10833.503,3735.5432,28572.076,31265.287,35112.55500,1290.43100,...,10463.9600,114518.83000,26769.357,37062.129,9840.7266,14450.682,1501.13890,3353.78930,2308.60380,2526.07230
2000,565.00000,5470.01760,10211.10400,3831.00000,14924.374,2918.5576,35244.504,38812.051,44791.52000,1645.71730,...,4797.3804,107206.46000,32961.527,45986.051,12874.7760,14417.104,2649.71950,3911.21970,2092.25510,2521.34740
2010,1662.80350,9927.17580,12898.29600,6492.17680,18794.270,6507.9146,41363.215,43174.977,39912.69500,2451.30520,...,7824.4985,57406.73800,36195.867,49372.832,17082.4100,16563.396,4486.26120,4481.55470,3263.39480,1388.97300

In [18]:
#read and show the dataset
df_sales=pd.read_excel("/content/supermarket_sales.xlsx")

In [20]:
df_sales

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33:00,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2019-01-29,13:46:00,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,17:16:00,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2019-02-09,13:22:00,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2019-02-22,15:33:00,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2019-02-18,13:28:00,Cash,618.38,4.761905,30.9190,6.6

In [23]:
#make pivot table and add aggregate function
df_sales.pivot_table(index="Gender", values=["Quantity", "Total", "cogs", "gross income"], aggfunc="sum").round(1)

        Quantity     Total      cogs  gross income
Gender
Female      2869  167882.9  159888.5        7994.4
Male        2641  155083.8  147698.9        7384.9

In [31]:
# make a pivot tables that says how much male and female spend in each category
df_sales.pivot_table(index='Gender',
                     columns='Product line',
                     values='Total',
                     aggfunc='sum').round(1)

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Gender,,,,,,
Female,27102.0,30437.4,33170.9,18561.0,30036.9,28574.7
Male,27235.5,23868.5,22973.9,30632.8,23825.0,26548.1