In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/rishirokde-official/Python-for-Data-Science/refs/heads/main/python-for-data-science-main/07.Project%202%20-%20Data%20Visualization/population_total.csv")

In [ ]:
df

            country    year    population
0             China  2020.0  1.439324e+09
1             China  2019.0  1.433784e+09
2             China  2018.0  1.427648e+09
3             China  2017.0  1.421022e+09
4             China  2016.0  1.414049e+09
...             ...     ...           ...
4180  United States  1965.0  1.997337e+08
4181  United States  1960.0  1.867206e+08
4182  United States  1955.0  1.716853e+08
4183          India  1960.0  4.505477e+08
4184          India  1955.0  4.098806e+08

[4185 rows x 3 columns]

In [ ]:
# dropping null values
df.dropna(inplace=True)

In [8]:
#making pivot table
df_pivot=df.pivot(index='year',columns='country',values='population')

In [9]:
df=df_pivot[['United States','India','China','Indonesia','Brazil']]

In [10]:
df

country  United States         India         China    Indonesia       Brazil
year
1955.0     171685336.0  4.098806e+08  6.122416e+08   77273425.0   62533919.0
1960.0     186720571.0  4.505477e+08  6.604081e+08   87751068.0   72179226.0
1965.0     199733676.0  4.991233e+08  7.242190e+08  100267062.0   83373530.0
1970.0     209513341.0  5.551898e+08  8.276014e+08  114793178.0   95113265.0
1975.0     219081251.0  6.231029e+08  9.262409e+08  130680727.0  107216205.0
1980.0     229476354.0  6.989528e+08  1.000089e+09  147447836.0  120694009.0
1985.0     240499825.0  7.843600e+08  1.075589e+09  164982451.0  135274080.0
1990.0     252120309.0  8.732778e+08  1.176884e+09  181413402.0  149003223.0
1995.0     265163745.0  9.639226e+08  1.240921e+09  196934260.0  162019896.0
2000.0     281710909.0  1.056576e+09  1.290551e+09  211513823.0  174790340.0
2005.0     294993511.0  1.147610e+09  1.330776e+09  226289470.0  186127103.0
2010.0     309011475.0  1.234281e+09  1.368811e+09  241834215.0  195713635.0
2015.0     320878310.0  1.310152e+09  1.406848e+09  258383256.0  204471769.0
2016.0     323015995.0  1.324517e+09  1.414049e+09  261556381.0  206163053.0
2017.0     325084756.0  1.338677e+09  1.421022e+09  264650963.0  207833823.0
2018.0     327096265.0  1.352642e+09  1.427648e+09  267670543.0  209469323.0
2019.0     329064917.0  1.366418e+09  1.433784e+09  270625568.0  211049527.0
2020.0     331002651.0  1.380004e+09  1.439324e+09  273523615.0  212559417.0