In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("https://www.football-data.co.uk/mmz4281/2526/P1.csv")

In [3]:
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,P1,08/08/2025,20:15,Casa Pia,Sp Lisbon,0,2,A,0,1,...,1.93,1.93,1.90,2.00,1.93,1.95,1.82,1.92,1.91,2.04
1,P1,09/08/2025,15:30,Nacional,Gil Vicente,0,2,A,0,2,...,1.80,2.05,1.89,2.02,1.83,2.05,1.78,1.97,1.87,2.12
2,P1,09/08/2025,20:30,Arouca,AVS,3,1,H,1,0,...,1.98,1.88,1.97,1.93,1.98,1.90,1.90,1.79,2.02,1.95
3,P1,10/08/2025,17:00,Famalicao,Santa Clara,3,0,H,2,0,...,1.93,1.93,2.00,1.90,1.93,1.93,1.78,1.89,1.93,2.05
4,P1,10/08/2025,20:30,Moreirense,Alverca,2,1,H,1,1,...,1.95,1.90,2.05,1.87,1.95,1.90,1.88,1.84,2.05,1.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,P1,16/05/2026,18:00,Nacional,Guimaraes,2,0,H,0,0,...,1.90,1.95,NaN,NaN,1.90,2.05,1.79,1.95,1.86,2.12
302,P1,16/05/2026,18:00,Sp Braga,Estrela,2,2,D,1,1,...,1.90,1.95,NaN,NaN,1.90,1.95,1.84,1.88,1.92,2.04
303,P1,16/05/2026,20:30,Estoril,Benfica,1,3,A,0,3,...,1.78,2.03,NaN,NaN,1.80,2.03,1.77,1.95,1.82,2.10
304,P1,16/05/2026,20:30,Famalicao,Alverca,1,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.98,1.95
305,P1,16/05/2026,20:30,Sp Lisbon,Gil Vicente,3,0,H,2,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.87,1.85,2.02,1.92

In [15]:
root="https://www.football-data.co.uk/mmz4281/"

In [19]:
root

'https://www.football-data.co.uk/mmz4281/'

In [20]:
#create list
leagues=['P1','P2']

frames=[]
for league in leagues:
  df= pd.read_csv(root + "2122" + "/" + league + ".csv")
  frames.append(df)

In [21]:
len(frames)

2

In [22]:
frames[1].head(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP2,13/08/2021,19:00,Huesca,Eibar,2,0,H,1,0,...,1.52,-0.25,1.95,1.90,1.97,1.93,1.99,1.97,1.93,1.91
1,SP2,13/08/2021,21:00,Zaragoza,Ibiza,0,0,D,0,0,...,1.42,-0.25,1.90,1.95,1.93,1.98,2.02,2.00,1.93,1.91
2,SP2,14/08/2021,16:00,Sociedad B,Leganes,1,0,H,0,0,...,1.45,0.25,1.83,2.02,1.85,2.07,1.87,2.12,1.82,2.03

In [25]:
#MULTIPLE SEASONS
league_codes=['P1','P2']

frames=[]
#LOOP THROUGH RANGE OF SEASON AND INSERT NEW COLUMN
for league_code in league_codes :
  for season in range (15,21):
    season_str_part = str(season) + str(season+1)
    df=pd.read_csv(root + season_str_part + "/" + league_code + ".csv")
    df.insert(1,'season',season)
    frames.append(df)

In [26]:
len(frames)

12

In [27]:
frames[10]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP2,19,17/08/2019,17:00,Lugo,Extremadura UD,0,0,D,0,...,1.61,-0.25,1.90,1.95,1.91,1.99,1.94,2.02,1.89,1.96
1,SP2,19,17/08/2019,17:00,Santander,Malaga,0,1,A,0,...,1.47,-0.50,1.95,1.90,2.04,1.85,2.06,1.95,1.99,1.86
2,SP2,19,17/08/2019,18:00,Almeria,Albacete,3,0,H,0,...,1.55,-0.25,1.93,1.93,1.93,1.97,1.98,1.98,1.92,1.93
3,SP2,19,17/08/2019,19:00,Elche,Fuenlabrada,0,2,A,0,...,1.48,-0.25,1.88,1.98,1.89,2.01,1.93,2.21,1.85,2.00
4,SP2,19,17/08/2019,20:00,Vallecano,Mirandes,2,2,D,2,...,1.82,-1.00,1.98,1.88,2.03,1.87,2.06,1.96,1.97,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,SP2,19,20/07/2020,20:00,Numancia,Tenerife,2,1,H,1,...,1.90,-0.75,1.83,2.02,1.87,2.03,1.88,2.12,1.83,2.02
458,SP2,19,20/07/2020,20:00,Santander,Vallecano,1,2,A,1,...,2.18,1.00,2.02,1.83,2.06,1.84,2.11,1.87,2.03,1.81
459,SP2,19,20/07/2020,20:00,Sp Gijon,Huesca,0,1,A,0,...,1.87,0.00,2.02,1.83,2.02,1.88,2.18,1.90,2.02,1.83
460,SP2,19,20/07/2020,20:00,Zaragoza,Ponferradina,2,1,H,1,...,1.93,0.00,1.70,2.10,1.72,2.21,1.87,2.21,1.74,2.12
461,SP2,19,07/08/2020,20:00,La Coruna,Fuenlabrada,2,1,H,0,...,1.83,0.00,1.85,2.00,1.88,1.97,2.15,2.08,1.87,1.98

In [28]:
frames[10].head(3)

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP2,19,17/08/2019,17:00,Lugo,Extremadura UD,0,0,D,0,...,1.61,-0.25,1.90,1.95,1.91,1.99,1.94,2.02,1.89,1.96
1,SP2,19,17/08/2019,17:00,Santander,Malaga,0,1,A,0,...,1.47,-0.50,1.95,1.90,2.04,1.85,2.06,1.95,1.99,1.86
2,SP2,19,17/08/2019,18:00,Almeria,Albacete,3,0,H,0,...,1.55,-0.25,1.93,1.93,1.93,1.97,1.98,1.98,1.92,1.93